version: "3.9"
services:
  communiditts_serv:
    build:
      context: .
    ports:
      - "3001:3001"
    links:
      - communiditts_db
    volumes:
      - .:/home/app
  communiditts_db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data

volumes:
  mongo-data:
